IPBundle\Entity\Mask:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        octets:
            type: string
            length: 255
    lifecycleCallbacks: {  }
