IPBundle\Entity\Eleve:
    properties:
        sexe:
            - Choice:
                choices: [male, female]
                message: Choose a valid gender. 

IPBundle\Model\IPAdress:
    properties:
        class:
            - Choice:
                choices: [a,A,b,B,c,C,d,D]
                message: Choose an existing class. 