ip:
    resource: "@IPBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    path: /index
    defaults: {_controller : IPBundle:Default:index}

addEleve:
    path: /addEleve
    defaults: {_controller : IPBundle:Database:addEleve}

addNoteEleve:
    path: /addNoteEleve/{valeur}/{cours}
    defaults: {_controller : IPBundle:Database:addNoteEleve}

showAllEleve:
    path: /showAllEleve
    defaults: {_controller : IPBundle:Database:showAllEleve}

showNotesEleve:
    path: /showNotesEleve/{prenom}
    defaults: {_controller : IPBundle:Database:showNotesEleve}

showNotesCours:
    path: /showNotesCours/{cours}
    defaults: {_controller : IPBundle:Database:showNotesCours}

showListeCours:
    path: /showListeCours
    defaults: {_controller : IPBundle:Database:showListeCours}

newEleve:
    path: /newEleve
    defaults: {_controller : IPBundle:Default:newEleve}

exoMask:
    path: /exoMask
    defaults: {_controller : IPBundle:Default:exoMask}

exoClass:
    path: /exoClass
    defaults: {_controller : IPBundle:Default:exoClass}

giveMask:
    path: /giveMask/{ipBytes}/{nbSubNet}
    defaults: {_controller : IPBundle:Default:giveMask}

routingTable:
    path: /routingTable
    defaults: {_controller : IPBundle:Default:routingTable}

login_route:
    path:     /login
    defaults: { _controller: IPBundle:Security:login}

newCours:
    path: /newCours
    defaults: {_controller: IPBundle:Default:newCours}

newChapitre:
    path: /newChapitre
    defaults: {_controller: IPBundle:Default:newChapitre}

showCours:
    path: /showCours/{id}
    defaults: {_controller: IPBundle:Default:showCours}

showAllCours:
    path: /showAllCours
    defaults: {_controller: IPBundle:Default:showAllCours}

exercises:
    path: /exercises
    defaults: {_controller: IPBundle:Default:exercises}

convert:
    path: /convert
    defaults: {_controller: IPBundle:Default:convert}

progression:
    path: /progression
    defaults: {_controller: IPBundle:Default:progression}

progressionCours:
    path: /progressionCours/{id}
    defaults: {_controller: IPBundle:Default:progressionCours}

showChapitre:
    path: /showChapitre/{id}
    defaults: {_controller: IPBundle:Default:showChapitre}

recupNotes:
    path: /recupNotes
    defaults: {_controller: IPBundle:Database:recupNotes}


login_check:
    path: /login_check
    # no controller is bound to this route
    # as it's handled by the Security system

logout:
    path: /logout