ip:
    resource: "@IPBundle/Resources/config/routing.yml"
    prefix:   /






  


index:
    path: /
    defaults: {_controller : IPBundle:Default:index}

addNoteEleve:
    path: /addNoteEleve/{valeur}/{cours}
    defaults: {_controller : IPBundle:Database:addNoteEleve}

showAllEleve:
    path: /showAllEleve
    defaults: {_controller : IPBundle:Database:showAllEleve}

showNotesEleve:
    path: /showNotesEleve/{prenom}
    defaults: {_controller : IPBundle:Database:showNotesEleve}

showNotesCours:
    path: /showNotesCours/{cours}
    defaults: {_controller : IPBundle:Database:showNotesCours}

showListeCours:
    path: /showListeCours
    defaults: {_controller : IPBundle:Database:showListeCours}

newEleve:
    path: /newEleve
    defaults: {_controller : IPBundle:Create:newEleve}

exoMask:
    path: /exoMask
    defaults: {_controller : IPBundle:Exo:exoMask}

exoClass:
    path: /exoClass
    defaults: {_controller : IPBundle:Exo:exoClass}

giveMask:
    path: /giveMask/{ipBytes}/{nbSubNet}
    defaults: {_controller : IPBundle:Default:giveMask}

routingTable:
    path: /routingTable
    defaults: {_controller : IPBundle:Exo:routingTable}

login_route:
    path:     /login
    defaults: { _controller: IPBundle:Security:login}

newCours:
    path: /newCours
    defaults: {_controller: IPBundle:Create:newCours}

newChapitre:
    path: /newChapitre
    defaults: {_controller: IPBundle:Create:newChapitre}

showCours:
    path: /showCours/{id}
    defaults: {_controller: IPBundle:Default:showCours}

showAllCours:
    path: /showAllCours
    defaults: {_controller: IPBundle:Default:showAllCours}

exercises:
    path: /exercises
    defaults: {_controller: IPBundle:Default:exercises}

convert:
    path: /convert
    defaults: {_controller: IPBundle:Exo:convert}

progression:
    path: /progression
    defaults: {_controller: IPBundle:Default:progression}

progressionCours:
    path: /progressionCours/{id}
    defaults: {_controller: IPBundle:Default:progressionCours}

progressionEleves:
    path: /progressionEleves
    defaults: {_controller: IPBundle:Default:progressionEleves}

progressionEleve:
    path: /progressionEleve\{id}
    defaults: {_controller: IPBundle:Default:progressionEleve}

showChapitre:
    path: /showChapitre/{id}
    defaults: {_controller: IPBundle:Default:showChapitre}

recupNotes:
    path: /recupNotes
    defaults: {_controller: IPBundle:Database:recupNotes}

compte:
    path: /compte
    defaults: {_controller: IPBundle:Default:compte}


login_check:
    path: /login_check
    # no controller is bound to this route
    # as it's handled by the Security system

logout:
    path: /logout

login:
    path: /login