ip:
    resource: "@IPBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

addEleve:
    path: /addEleve
    defaults: {_controller : IPBundle:Database:addEleve}

addNoteEleve:
    path: /addNoteEleve/{valeur}/{idEleve}
    defaults: {_controller : IPBundle:Database:addNoteEleve}

showAllEleve:
    path: /showAllEleve
    defaults: {_controller : IPBundle:Database:showAllEleve}

showNotesEleve:
    path: /showNotesEleve/{idEleve}
    defaults: {_controller : IPBundle:Database:showNotesEleve}

newEleve:
    path: /newEleve
    defaults: {_controller : IPBundle:Default:newEleve}

exoMask:
    path: /exoMask
    defaults: {_controller : IPBundle:Default:exoMask}

exoClass:
    path: /exoClass
    defaults: {_controller : IPBundle:Default:exoClass}

giveMask:
    path: /giveMask/{ipBytes}/{nbSubNet}
    defaults: {_controller : IPBundle:Default:giveMask}