# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        IPBundle\Entity\Eleve:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

        our_db_provider:
            entity:
                class: IPBundle:Eleve
                property: username

    role_hierarchy:
            ROLE_PROF: ROLE_USER

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: /login
                check_path: /login_check
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            provider: our_db_provider

            logout:
                path:   /logout
                target: /index